apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-carrito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-carrito
  template:
    metadata:
      labels:
        app: redis-carrito
    spec:
      containers:
        - name: redis
          image: redis:7.4
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-carrito
spec:
  selector:
    app: redis-carrito
  ports:
    - port: 6379