apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
        - name: inventario
          image: gilgamesh06/inventario:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-inventario:5432/ecommerce_inventario
            - name: SPRING_DATASOURCE_USERNAME
              value: Solus
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: admin
            - name: SPRING_RABBITMQ_PASSWORD
              value: "123456"
