apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  type: NodePort
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30000
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
      nodePort: 30443
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 30001
