apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong/kong-gateway:3.10-debian
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /usr/local/kong/kong.yml
            - name: KONG_PROXY_LISTEN
              value: 0.0.0.0:8000, 0.0.0.0:8443 ssl
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
          volumeMounts:
            - name: kong-config
              mountPath: /usr/local/kong/kong.yml
              subPath: kong.yml
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
